# Generated by Django 4.2.7 on 2025-12-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('warnings', models.IntegerField(default=0)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.test')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('student_user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='CheatingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('tab_switch', 'Tab Switched'), ('fullscreen_exit', 'Exited Fullscreen'), ('window_blur', 'Window Lost Focus'), ('right_click', 'Right Click Detected'), ('copy_paste', 'Copy/Paste Detected'), ('developer_tools', 'Developer Tools Opened')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_attempts', to='exam.examsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
